version: "3.9"

services:

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    depends_on:
      - selenium-hub
    shm_size: "2gb"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSION_TIMEOUT=300
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=1

  firefox:
    image: selenium/node-firefox:latest
    container_name: firefox
    depends_on:
      - selenium-hub
    shm_size: "2gb"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSION_TIMEOUT=300
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=1

  edge:
    image: selenium/node-edge:latest
    container_name: edge
    depends_on:
      - selenium-hub
    shm_size: "2gb"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSION_TIMEOUT=300
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=1

  chrome_video:
    image: selenium/video:ffmpeg-8.0-20251202
    depends_on:
      - chrome
    volumes:
      - ./Vidio_Recordings:/videos
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_VIDEO_FILE_NAME=auto

  firefox_video:
    image: selenium/video:ffmpeg-8.0-20251202
    depends_on:
      - firefox
    volumes:
      - ./Vidio_Recordings:/videos
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_VIDEO_FILE_NAME=auto

  edge_video:
    image: selenium/video:ffmpeg-8.0-20251202
    depends_on:
      - edge
    volumes:
      - ./Vidio_Recordings:/videos
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_VIDEO_FILE_NAME=auto

  file_browser:
    image: filebrowser/filebrowser:latest
    container_name: file_browser
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./Vidio_Recordings:/srv
    environment:
      - FB_NOAUTH=true

  test-runner:
    build: .
    depends_on:
      - selenium-hub
    environment:
      - GRID_URL=http://selenium-hub:4444/wd/hub
